version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - 'MYSQL_DATABASE=what_the_weather_db'
      - 'MYSQL_ROOT_PASSWORD=wtw2024'
      - 'MYSQL_USER=wtw'
      - 'MYSQL_PASSWORD=wtw2024'
      - 'TZ=Asia/Seoul'
    ports:
      - '33306:3306'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
